# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ZZweETr5gPmMFJYnuXcllMW9sqVVQkW
"""

# Install necessary libraries
!pip install streamlit plotly pandas

# Streamlit application script
import streamlit as st
import pandas as pd
import plotly.express as px

# Load the dataset from GitHub
url = 'https://github.com/satyam26en/JOB/blob/main/Clean_Job_File.csv?raw=true'
job_data = pd.read_csv(url)

# Calculate average rating and total reviews per company
company_ratings = job_data.groupby('company')['rating'].mean().reset_index().rename(columns={'rating': 'average_rating'})
company_reviews = job_data.groupby('company')['reviews'].sum().reset_index().rename(columns={'reviews': 'total_reviews'})
combined_company_data = company_ratings.merge(company_reviews, on='company')

# Streamlit App
st.title("Company Insights Dashboard")

# Filter by location
locations = job_data['location'].unique()
selected_location = st.selectbox("Select Location", locations)
filtered_data = job_data[job_data['location'] == selected_location]

# Calculate metrics for the selected location
company_ratings_location = filtered_data.groupby('company')['rating'].mean().reset_index().rename(columns={'rating': 'average_rating'})
company_reviews_location = filtered_data.groupby('company')['reviews'].sum().reset_index().rename(columns={'reviews': 'total_reviews'})
combined_company_data_location = company_ratings_location.merge(company_reviews_location, on='company')

# Top 10 Companies based on average rating and total reviews
top_10_companies = combined_company_data_location.sort_values(by=['average_rating', 'total_reviews'], ascending=[False, False]).head(10)

# Plotly Bar Chart for Top 10 Companies
fig = px.bar(top_10_companies, x='company', y='average_rating',
             hover_data=['total_reviews'], color='average_rating',
             labels={'average_rating': 'Average Rating'},
             title='Top 10 Companies Based on Ratings and Reviews')

st.plotly_chart(fig)

# Rating Distribution Chart
rating_distribution = filtered_data['rating'].value_counts().sort_index()
fig2 = px.bar(rating_distribution, x=rating_distribution.index, y=rating_distribution.values,
              labels={'index': 'Rating', 'y': 'Count'},
              title='Rating Distribution')
st.plotly_chart(fig2)