# -*- coding: utf-8 -*-
"""JOBS2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17DwPfhC90f2mnQwuV7wgQr8tMcIvEJbR
"""

import streamlit as st
import pandas as pd
import plotly.express as px

st.title("Job Analysis Dashboard")

# Load the dataset
file_url = "https://raw.githubusercontent.com/satyam26en/JOB/main/Clean_Job_File.csv"
df = pd.read_csv(file_url)

# Part 1: Average Ratings and Reviews by Company
st.header("Part 1: Average Ratings and Reviews by Company")
def plot_average_ratings_reviews(df):
    average_ratings_reviews = df.groupby('company').agg({'rating': 'mean', 'reviews': 'sum'}).reset_index()
    average_ratings_reviews.columns = ['company', 'average_rating', 'total_reviews']
    min_reviews = 1000
    filtered_ratings_reviews = average_ratings_reviews[average_ratings_reviews['total_reviews'] >= min_reviews]
    filtered_ratings_reviews = filtered_ratings_reviews.sort_values(by='average_rating', ascending=False)
    top_10_ratings = {
        "0-2 Stars": filtered_ratings_reviews.query("average_rating <= 2").head(10),
        "2-3.5 Stars": filtered_ratings_reviews.query("average_rating > 2 and average_rating <= 3.5").head(10),
        "3.5-4.5 Stars": filtered_ratings_reviews.query("average_rating > 3.5 and average_rating <= 4.5").head(10),
        "> 4.5 Stars": filtered_ratings_reviews.query("average_rating > 4.5").head(10),
        "All Ratings": filtered_ratings_reviews.head(10)
    }
    fig = px.bar(top_10_ratings["All Ratings"], x='company', y='average_rating', title='Top 10 Companies by Average Ratings and Reviews', hover_data={'total_reviews': True})
    filters = [
        dict(
            args=[{"x": [top_10_ratings["0-2 Stars"]['company']], "y": [top_10_ratings["0-2 Stars"]['average_rating']], "hover_data": {'total_reviews': True}}],
            label="0-2 Stars",
            method="restyle"
        ),
        dict(
            args=[{"x": [top_10_ratings["2-3.5 Stars"]['company']], "y": [top_10_ratings["2-3.5 Stars"]['average_rating']], "hover_data": {'total_reviews': True}}],
            label="2-3.5 Stars",
            method="restyle"
        ),
        dict(
            args=[{"x": [top_10_ratings["3.5-4.5 Stars"]['company']], "y": [top_10_ratings["3.5-4.5 Stars"]['average_rating']], "hover_data": {'total_reviews': True}}],
            label="3.5-4.5 Stars",
            method="restyle"
        ),
        dict(
            args=[{"x": [top_10_ratings["> 4.5 Stars"]['company']], "y": [top_10_ratings["> 4.5 Stars"]['average_rating']], "hover_data": {'total_reviews': True}}],
            label="> 4.5 Stars",
            method="restyle"
        ),
        dict(
            args=[{"x": [top_10_ratings["All Ratings"]['company']], "y": [top_10_ratings["All Ratings"]['average_rating']], "hover_data": {'total_reviews': True}}],
            label="All Ratings",
            method="restyle"
        )
    ]
    fig.update_layout(
        title={
            'text': 'Top 10 Companies by Average Ratings and Reviews',
            'y':0.9,
            'x':0.5,
            'xanchor': 'center',
            'yanchor': 'top'
        },
        updatemenus=[
            dict(
                buttons=filters,
                direction="down",
                pad={"r": 10, "t": 10},
                showactive=True,
                x=1,
                xanchor="right",
                y=1.15,
                yanchor="top",
                bgcolor='rgba(255, 255, 255, 0.8)',
                bordercolor='black',
                borderwidth=1
            ),
        ]
    )
    st.plotly_chart(fig)

plot_average_ratings_reviews(df)

# Part 2: Number of Job Postings per Company
st.header("Part 2: Number of Job Postings per Company")
def plot_job_postings(df):
    company_job_counts = df['company'].value_counts().reset_index()
    company_job_counts.columns = ['company', 'job_postings']
    fig = px.bar(company_job_counts, x='company', y='job_postings', title='Number of Job Postings per Company', labels={'job_postings': 'Number of Job Postings', 'company': 'Company'})
    fig.update_layout(
        title={
            'text': 'Number of Job Postings per Company',
            'y':0.9,
            'x':0.5,
            'xanchor': 'center',
            'yanchor': 'top'
        },
        title_font_size=24,
        xaxis_title_font_size=20,
        yaxis_title_font_size=20,
        legend_title_text='Company Ranking',
        legend_title_font_size=20,
        legend_font_size=16,
        legend=dict(
            x=0,
            y=1,
            xanchor='left',
            yanchor='top'
        ),
        updatemenus=[
            dict(
                buttons=list([
                    dict(
                        args=[{"y": [company_job_counts['job_postings'][:10]]}],
                        label="Top 10 Companies",
                        method="restyle"
                    ),
                    dict(
                        args=[{"y": [company_job_counts['job_postings'][-10:]]}],
                        label="Bottom 10 Companies",
                        method="restyle"
                    ),
                    dict(
                        args=[{"y": [company_job_counts['job_postings']]}],
                        label="All Companies",
                        method="restyle"
                    )
                ]),
                direction="down",
                pad={"r": 10, "t": 10},
                showactive=True,
                x=1,
                xanchor="right",
                y=1.15,
                yanchor="top",
                bgcolor='rgba(255, 255, 255, 0.8)',
                bordercolor='black',
                borderwidth=1
            ),
        ]
    )
    fig.update_traces(marker=dict(line=dict(width=1, color='DarkSlateGrey')),
                    selector=dict(type='bar'))
    st.plotly_chart(fig)

plot_job_postings(df)

# Part 3: Top 10 Locations Based on Number of Job Openings
st.header("Part 3: Top 10 Locations Based on Number of Job Openings")
def plot_location_clusters():
    data = {
        'location': [
            'Bangalore/Bengaluru', 'Hyderabad/Secunderabad', 'Mumbai',
            'Delhi / Ncr', 'Gurgaon/Gurugram', 'Pune', 'Chennai', 'Noida'
        ],
        'job_openings': [11357, 6648, 5686, 4827, 4701, 3524, 3254, 2604],
        'lat': [12.9716, 17.3850, 19.0760, 28.6139, 28.4595, 18.5204, 13.0827, 28.5355],
        'lon': [77.5946, 78.4867, 72.8777, 77.2090, 77.0266, 73.8567, 80.2707, 77.3910]
    }
    df = pd.DataFrame(data)
    fig = px.scatter_geo(df,
                         lat="lat",
                         lon="lon",
                         size="job_openings",
                         color="job_openings",
                         color_continuous_scale="Plasma",
                         title="Specified Company Location Clusters in India",
                         hover_name="location",
                         hover_data=["job_openings"],
                         projection="natural earth")
    fig.update_geos(
        visible=False,
        resolution=50,
        showcountries=True, countrycolor="Black",
        showsubunits=True, subunitcolor="Blue",
        projection_scale=5,
        center=dict(lat=20.5937, lon=78.9629)
    )
    fig.update_layout(
        title={
            'text': 'Top 10 Locations Based on Number of Job Openings',
            'y':0.9,
            'x':0.5,
            'xanchor': 'center',