# -*- coding: utf-8 -*-
"""Shooping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bp4ok7alsjzWvmQ1RFSa1g1px1liAy_9
"""

import streamlit as st

def calculate_total_cost(my_dict):
    total_cost = 0

    st.write(f"{'Product Name':<15}{'Price':<10}{'Quantity':<10}")
    st.write("-" * 35)

    table_data = []

    for item in my_dict:
        amount = float(my_dict[item]['amount'])
        quantity = int(my_dict[item]['quantity'])
        total_cost += amount * quantity

        table_data.append({
            "Product Name": item,
            "Price": amount,
            "Quantity": quantity
        })

    st.table(table_data)
    st.write("-" * 35)
    st.write(f"**Total Bill:** {total_cost}")

st.title("Shopping Cart")

my_dict = {}
while True:
    key = st.text_input("Enter the product name (or leave blank and press Enter if you completed your shopping): ")

    if not key:
        break

    amount = st.number_input(f"Enter the price for {key}:", min_value=0.0, format="%.2f")
    quantity = st.number_input(f"Enter the number of quantity for {key}:", min_value=1, step=1)

    my_dict[key] = {'amount': amount, 'quantity': quantity}

    st.write("### Shopping Cart")
    calculate_total_cost(my_dict)